spring:
  cloud:
    gateway:
      routes:
        - id: business-server
          uri: http://localhost:10011
          predicates:
            - Path=/auth/business/**
          filters: #表示去掉api前缀
            - StripPrefix=2
        - id: sso-SERVER
          uri: http://localhost:10010
          predicates:
            - Path=/auth/api/**
            - Cookie=authcode, (.*)
          filters:
            - StripPrefix=2